# Generated by Django 5.1.1 on 2024-10-20 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='updated',
        ),
    ]
